## The Concept of Democratic Support

There are two major conceptualizations of public support for democracy (PSD). First, the "implicit" approach that requires the support for broader sociopolitical values like post-materialism and egalitarianism. Here, people support democracy implicitly if they support the values that are framed as particularly democratic. Second, the "explicit" approach that requires both an appraisal of democracy and a rejection of autocratic alternatives. Some studies also refer to PSD measured on the national level as "mood". 

## Drivers of Democratic Support

The main theory about why citizen and societies begin to support democracy are called *generational socialization* and *instrumental regime performance*. The first theory assumes that individuals are taught to support the regime under which they are socialized during late adolescence [@Niemi1974; @Mannheim1970]. One implication is that after a shift to democracy, the support for it will grow over time (@Denemark2016). Indeed, several single-country studies have found evidence for this claim, for example for 1970s Germany (@Baker1981), 1980s Spain (@Montero1997), and 1990s Russia (@Mishler2007). One the other hand, other studies do not find such an effect analyzing other Central and Eastern European countries (@Mishler2002). Furthermore, more recent studies even find a decline in PSD over the last years [@Foa2016; @Foa2017].

Regarding the second theory, instrumental regime performance, PSD rises if the system performs well in terms of instrumental benefits such as economic growth and it declines if the opposite is the case [@Dalton1994; @Magalhaes2014]. Consequently, the theory suggests that during PSD declines during economic crises. However, there are case-studies that do [@Dalton1994; @Magalhaes2014; @Mishler1996] and that do not (@Graham2004) find this relationship in the data.

@Claassen2020mood offers an alternative theory in transferring the thermostatic model of public opinion and policy (@Wlezien1995) to democracy and democratic support. In particular, he suggests that there is a negative feedback loop between PSD and democracy so that PSD decreases if democracy supply increases and vice versa. In short, the reasoning is that the output of democratic rights and institutions overshoots the initial desire for them which causes another overcompensation in favor of lower levels of democracy. Moreover, @Claassen2020mood finds different causal channels for electoral and minoritarian democracies. These two sub-types differ in the degree to which the majority holds juridical power. Therefore, he tests the following hypotheses: First, increases in democracy have a negative effect on PSD (H1), Second, he specifically looks at electoral (H1-elec) and minoritarian democracies (H1-min). In his analysis he finds evidence for H1 and H1-min but not for H1-elec.

## Democratic Support and Survival of Democracy

@Claassen2020support distinguishes between two types of PSD: diffuse and specific. Specific PSD is instrumental and focuses on regime outputs (similar to the instrumental regime performance theory), whereas diffuse support is normative and focuses on the principles of the regime. Therefore, principled PSD is more durable than specific support and helps cushioning regimes in times of political or economic crises. It is thus principled PSD that helps to ensure the survival of democracy. Although the theory is widely accepted (e.g., @Norris2017, @Booth2009, @Mattes2007), the findings so far have also been mixed with supporting contributions [@Inglehart2003; @Welzel2005] and contributions against the theory [@Hadenius2005; @Welzel2007; @Fails2010; @Qi2011]. Astonishingly, these studies essentially analyze the same data from the World Value Survey starting at wave 3 where respective PSD items are included.

@Claassen2020support does not only look at the relationship between PSD and democractic survival but also between PSD and democratic emergence. He includes the argument made by @Qi2011 that PSD may also function as democratic demand, thus increasing the probability of transitioning from autocracy to democracy. Claassens hypotheses thus are: First, PSD is positively associated with subsequent change in democracy regardless of the initial level of democracy. Second, he specifically looks at PSD in already-existing democracies (H2-dem) and at PSD in autocracies (H2-aut). He finds evidence in support of H2-dem, mixed evidence for H2 and no evidence for H2-aut.

## Measuring Democratic Support and the Data Challenge

### Problems in previous studies

We measure PSD with existing survey data on the national level. In particular, we focus on principled support. The questions ask for the respondent's opinion on the appropriateness or desirability of democracy and undemocratic alternatives and comparisons between both.

Such items are available in 14 survey projects ^[World and European Values Surveys, the Afrobarometer, Arab Barometer, Latinobarometer, Asiabarometer, Asian Barometer, South Asia Barometer, New Europe Barometer, Latin American Public Opinion Project, Eurobarometer, European Social Survey, pew Global Attitudes Project, and the Comparative Study of Electoral Systems], for 150 countries, and from 1988 on. Combined, the dataset includes 3,765 nationally aggregated binary responses from 1,390 nationally representative survey samples.

The data, however, poses the following challenge: It is highly fractured across time and space, with many -- oftentimes large -- gaps for all countries except Belgium. For instance, China is the country with most participants over all years, namely 20895. However, from 1988 to 2020, the data available covers only 2001-2003, 2006-2009, and 2011/2012. And this is even a good coverage. Many countries are not covered at all or only surveyed once (insert numbers and code).

So far, past research has responded to this issue by discarding most of the available data and using only small cross-sectional data sets consisting of data from only one survey project for one year.

### Data and items  and small sketch of the approach as intro to next section

Both publications use panel data for PSD in many countries and measured by multiple items. However, the respective datasets display many gaps. To solve this problem, Claassen describes a method to estimate the data in the first publication of the three-part series, @Claassen2019estimating.
