---
title: "On Using the Metropolis-Hastings Algorithm for Data Imputation"
author: "Tobias Stenzel"
date: "`r format(Sys.time(), '%B %d, %Y')`"
header-includes:
   - \usepackage{tikz, float, caption, amsthm, algorithm, algpseudocode}
   - \floatplacement{figure}{H}
   #- \newtheorem{definition}{Definition}
   - \interfootnotelinepenalty=10000 # no multi-page footnotes
output:
  bookdown::pdf_document2:
    template: template.tex
    latex_engine: xelatex
    toc: yes
    toc_depth: 2
    keep_tex: yes
  html_document:
    toc: yes
    toc_depth: '2'
    df_print: paged
bibliography: bibliography.bib
csl-hanging-indent: yes
fontsize: 12pt 
linestretch: 2.0 # adjust for line spacing 
geometry: left=2.5cm,right=2.5cm,top=2.5cm,bottom=2.5cm
classoption:
- a4paper
- oneside
lang: en-EN
numbersections: yes
csquotes: yes
type: Final Paper for Course
course: Advanced Quantitative Methods in Political Science
subtitle: ''
address: ''
email: tobias.stenzel@students.uni-mannheim.de
phone: ''
examiner: Prof. Thomas Gschwend, Ph.D.
chair: ''
mp: 0.55
ID: ''
# STRONGLY BIASED wordcount: '*Wordcount excluding References: `r unima::count_words(knitr::current_input())`*' 
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/american-political-science-association.csl
editor_options:
  markdown:
    wrap: sentence
---
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      include=FALSE,
                      fig.path = "figs/",
                      out.width="\\textwidth"
                      )

p_needed <- c(# all packages you need to install here
  "knitr",
  "bookdown", # referencing figures and tables by label
  "remotes",
  "ggplot2",
  "stargazer",
  "dplyr", # to compute leads values
  "tidyr", # for dropping nans
  "GGally", # correlation matrix style plots
  "gridExtra", # grid for multiple plots
  "cowplot",
  "MASS", # glm
  "janitor", # fd plot over range
  #"countreg", # rootogram
  "ggeasy", # remove axes
  "latex2exp", # latex legend labels
  "ggridges"
  )


# installs only the required packages 
lapply(p_needed[!(p_needed %in% rownames(installed.packages()))], install.packages)
lapply(p_needed, library, character.only = TRUE)

# separately install for the correct wordcount package 
if (!"unima" %in% rownames(installed.packages())){
  remotes::install_github("vktrsmnv/unima-template", upgrade = "never", dependencies = TRUE)
  }

# this allows you to add notes to figures with a simple chunk option
# you only need to add "notes="text" as a chunk option; 
# the notes will only appear in PDF output
hook_chunk = knit_hooks$get('chunk')
knit_hooks$set(chunk = function(x, options) {
  txt = hook_chunk(x, options)
  # add chunk option 'description' which adds \Description{...} to figures
  if (!is.null(options$notes)) {
    latex_include <- paste0("\\\\vspace\\{0.5cm\\} \\\\\\footnotesize\\{\\\\textit\\{Notes: \\}", options$notes, "\\} \\1")
    gsub('(\\\\end\\{figure\\})', latex_include, txt) 
  } else {
    return(txt)  # pass to default hook
  }
})
if (knitr::is_latex_output()) knitr::knit_hooks$set(plot = knitr::hook_plot_tex)

# This is an option for stargazer tables
# It automatically adapts the output to html or latex,
# depending on whether we want a html or pdf file
stargazer_opt <- ifelse(knitr::is_latex_output(), "latex", "html")

# This ensures that if the file is knitted to HTML,
# significance notes are depicted correctly 
if (stargazer_opt == "html"){
  fargs <- formals(stargazer)
  fargs$notes.append = FALSE
  fargs$notes = c("<em>&#42;p&lt;0.1;&#42;&#42;p&lt;0.05;&#42;&#42;&#42;p&lt;0.01</em>")
  formals(stargazer) <- fargs
}

# only relevant for ggplot2 plotting
# setting a global ggplot theme for the entire document to avoid 
# setting this individually for each plot 
theme_set(theme_classic() + # start with classic theme 
  theme(
    plot.background = element_blank(),# remove all background 
    plot.title.position = "plot", # move the plot title start slightly 
    legend.position = "bottom" # by default, put legend on the bottom
  ))

set.seed(2021)

```
# Background

## Introduction

The Metropolis-Hastings (MH) algorithm is a method for sampling data points from a probability distribution. It places among the top 10 algorithms with the greatest influence on science and engineering in the 20th century [@beichl2000metropolis]. The MH algorithm belongs to the class of Markov chain Monte Carlo (MCMC) methods. In my explanation I assume prior knowledge on Monte Carlo sampling. However, I will explain the basics of Markov Chains. This section is structured as follows. First, I motivate the usage of the MH algorithm. Second, I explain the basics of Markov Chains. Third, I present the algorithm, and finally, I show why it works.

## Motivation

One main application for the MH algorithm is Bayesian inference. Specifically, we want to estimate parameters $\theta$ of some probabilistic model $f$. We have only limited prior knowledge of the distribution of $\theta$ and we have a likelihood sample of $f$. The goal is to estimate the posterior distribution of $\theta$ given all information that we have. In practice, we do not have a formal definition of the likelihood but only observations. Therefore, we can only approximate the posterior by numerical integration. This means, we can sample from the posterior and, for example, compute summary statistics like mean and variance of $\theta$. @claassen2019estimating assumes a model $f$ parametrized by $\theta$ and uses incomplete panel data as the likelihood. Then, he estimates the parameter distribution from the posterior obtained by the MH algorithm. In a final step, he uses the parameter estimates and samples the missing observations from the probabilistic model $f$.

## Markov Chains

A Markov chain is a stochastic process (over time) with the property that the probability of the realization in the next period depends solely on the realization in the current state and not the complete history. This is called the Markov property. Because discrete Markov chains are much more accessible than their continuous variant, in this chapter we will only look at the discrete case. Formally, the Markov property writes

\begin{equation}
(\#eq:markov-property)
P(X_{t+1} |X_{t}, X_{t-1}, ..., X_{0}) = P(X_{t+1} |X_{t}).
\end{equation}

\noindent
Under some conditions, the stochastic process described by a Markov chain converges to a time-invariant probability distribution, i.e. $P(X_{t+k} |X_{t+k-1}) = P(X_{t} |X_{t-1}), \forall k>0$. The crucial step for understanding the MH is to see how it samples a Markov Chain that is certain to converge to a stable posterior distribution. Before exploring how the MH algorithm employs these conditions, however, it is necessary to understand them conceptually. To this end, we will use the example depicted by the following graph in Figure 1 that shows the intertemporal transition probabilities between three states representing random events.


\begin{figure}[H]
(\#fig:ex1)


\centering

\begin{tikzpicture}[->,shorten >=1pt,auto,node distance=4cm,
                thick,main node/.style={circle,draw,font=\Large\bfseries}]

  \node[main node] (2) {2};
  \node[main node] (1) [below left of=2] {1};
  \node[main node] (3) [below right of=2] {3};

  \path
    (2) edge [loop above] node {0.1} (2)
        edge [bend left] node {0.9} (3)
    (1) edge [bend left] node {1} (2)
    (3) edge [bend left] node {0.6} (1)
        edge [bend left] node {0.4} (2);      
\end{tikzpicture}

\caption{Transition Graph for Markov Chain with 3 states.}
\end{figure}

\noindent
This transition graph can be summarized by the $n \times n$ transition matrix T where each element $(i,j)$ represents the probability of moving from state $i$ in period $t$ to state $k$ in period $t+1$, and where $n$ represents the number of states, i.e $T_{i,j} = P(X_{t+1}=j | X_t = i)$. For our example, we have

\begin{equation}
(\#eq:transition-matrix)
T=
\begin{pmatrix}
0 & 1 & 0\\
0 & 0.1 & 0.9\\
0.6 & 0.4 & 0
\end{pmatrix}\end{equation}

### Limit Distribution

As touched upon in the previous subsection, interesting questions can be what the probabilities of each state $j \in \{1, ..., s\}$ are after a finite number or infinitely many steps. For this purpose let $\pi (j) = P(X_t = j)$ denote the probability of being in state $j$ in period $t$. Of course, the probabilities in $t>0 $depend on the probabilities for the  the initial state $\pi_0$. We can use the law of total probability to calculate the probability of each state for the next period $t=1$ by 

\begin{equation}
(\#eq:tot-prob)
P(X_1 = j) = \sum_{i=1}^{3} P(X_1 = j | X_0 = i) \pi_0(i).
\end{equation}

\noindent
I.e., to compute the probability of being in state $j$ in $t=1$, for each initial state $i$, we multiply its probability $\pi_0(i)$ by the probability of moving from $i$ to state $j$. This is equivalent to $\pi_1 = \pi_0 T$ in vector notation. Further, we can compute the distributions for distributions locatet in more distant time by repeating the matrix multiplication, e.g, $\pi_2 = \pi_0 T T$, or in general, $\pi_t = \pi_0 T^t$.

Now we are ready to define the limit distribution that describes the probability distribution after infinitely many periods by

\begin{equation}
(\#eq:lim-dist)
\pi_{\infty} = lim_{t \rightarrow \infty} \pi_t = lim_{t \rightarrow \infty} \pi_0 T^t.
\end{equation}

\noindent
We can further ask two additional important questions. First, does a limit distribution exist? And second, is it unique, or in other word, do we have the same limit distribution independent from the realization of the initial state $X_0$? In our example, there does not only exist a limit distrubtion with $\pi_{\infty} = (0.2, 0.4, 0.4)$, it is even unique regardless of start distribution $\pi_0$!. This means that regardless of the start state, the probability of each state converges to the same number. For the context of the MH algorithm, this is an important property because we always want to compute the same estimates for our parameters $\theta$, regardless of the starting values of our simulation. In the next section, we introduce and simplify conditions that guarantee a unique limit distribution.

### Irreducibility, Periodicity and Stationarity

\begin{definition}
A Markov chain is called irreducible if each state is reachable from any other state in a finite number of steps.
\end{definition}

\noindent
Figure 2 shows two times the graph in Figure 1 combined to one Markov chain represented by a bipartite graph. Obviously, this chain is not irreducible because the initial state impacts all future distributions. More precisely, starting in one subgraphs sets the probability of reaching states in the other subgraph to zero. We see that a Markov Chain is only irreducible if there is an indirect link between every pair of states. We also observe that there can be no limit distribution if the Markov Chain is not irreducible.

\begin{figure}[H]
\label{fig:ex2}
\centering

\begin{tikzpicture}[->,shorten >=1pt,auto,node distance=3cm,thick,main node/.style={circle,draw,font=\Large\bfseries}]

  \node[main node] (2) {2};
  \node[main node] (1) [below left of=2] {1};
  \node[main node] (3) [below right of=2] {3};
  \node[main node] (4) [right of=3]{4};
  \node[main node] (5) [above right of=4] {5};
  \node[main node] (6) [below right of=5] {6};


  \path
    (2) edge [loop above] node {0.1} (2)
        edge [bend left] node {0.9} (3)
    (1) edge [bend left] node {1} (2)
    (3) edge [bend left] node {0.6} (1)
        edge [bend left] node {0.4} (2)
    (5) edge [loop above] node {0.1} (5)
        edge [bend left] node {0.9} (6)
    (4) edge [bend left] node {1} (5)
    (6) edge [bend left] node {0.6} (4)
        edge [bend left] node {0.4} (5); 
\end{tikzpicture}

\caption{Transition Graph for Irreducible Markov Chain.}

\end{figure}


\begin{definition}
A state $i$ has a period $k$ if the greatest common denominator of possible revisits is $k$. A Markov chain is aperiodic if the period of all its states is 1.
\end{definition}

\noindent
Consider the five-state Markov chain in Figure 3 as an illustration for the above definition and suppose we start in state 1. Observe that, independent of the random draw for next period, we will arrive again in state 1 after two or four steps. Therefore, state 1 has a period of 2. If a state is revisited in random rather than a fixed time period then the state has period 1. This is automatically the case if a state has a positive edge to itself.

\begin{figure}[H]
\label{fig:ex3}
\centering

\begin{tikzpicture}[->,shorten >=1pt,auto,node distance=3cm,thick,main node/.style={circle,draw,font=\Large\bfseries}]
  
  
  	\node[main node] (1) {1}; 
  	\node[main node] (2) [right of=1] {2};
  	\node[main node] (3) [below of=1] {3};
  	\node[main node] (4) [left of=1] {4}; 	
  	\node[main node] (5) [left of=4] {5}; 	


   \path
    (1) edge [bend left] node {1/3} (2)
    (1) edge [bend left] node[right] {1/3} (3)
    (1) edge [bend left] node {1/3} (4)

    
    (2) edge [bend left] node {1} (1)
    
    (3) edge [bend left] node {1} (1)
    
    (4) edge [bend left] node {1} (5)
    (5) edge [bend left] node {1} (4)
    (4) edge [bend left] node {1} (1);



  \end{tikzpicture}
  
  \caption{Markov Chain with 2-periodic State 1}

\end{figure}


\begin{definition}
$\pi^*$ is the stationary distribution of a Markov Chain with Transition matrix T if $\pi^* = \pi^* T$ and $\pi^*$ is a probability vector.
\end{definition}

\noindent
Verbally, this means that the probability distribution $\pi^*$ does not change anymore over time. If $\pi^*$ is also unique, then $\pi^*$ is our aim, the limit distribution introduces in section 1.3.1, i.e., $\pi^*=\pi_{\infty}$.

These three definitions are enough to understand the next fundamental theorem.

### The Fundamental Theorem of Markov Chains

The next theorem defines formally the condition when a Markov Chain converges to a unique distribution.

\begin{theorem} (Fundamental Theorem of Markov Chains)
If a Markov chain is irreducible and aperiodic (called ergodic) then it has a stationary distribution $\pi^*$ that is unique ($\lim_{t \rightarrow \infty} P(X_t = i) = \pi_i^*, \forall i$).
\end{theorem}

\noindent
Therefore, if we want to construct a stable distribution $p(\theta)$ via Markov chains, we need to ensure that it is irreducible and aperiodic with stationary distribution $\pi^*=p(\theta)$. In the next subsection, we substitute the stationarity condition by a stronger one before we finally come to the MH algorithm.

### Reversibility

\begin{definition}
A Markov chain is reversible if there is a probability distribution $\pi$ over its states such that $\pi(i) T_{ij} = \pi(j)T_{j,i}, \forall i,j$ (reversibility condition).
\end{definition}

\begin{theorem}
A sufficient condition for distribution $\pi^*$ to be a stationary distribution of a Markov chain with transition matrix T is that it fullfills the reversibility condition.
\end{theorem}

\begin{proof}
$\sum_i \pi(i) T_{i,j} = \sum_i \pi(j) T_{j,i} = \pi(j) \sum_i  T_{j,i} = \pi(j) \implies \pi T = \pi$
\end{proof}

Reversibility is a stronger condition than stationarity because it requires that the probability flux from $i$ to $j$ is equal to the one from $j$ to $i$ for each possible pair of states. Recall, that stationarity only requires that the probability flux to one state is equal on aggregate and not that it is symmetric between each pair of states over time.


## The Algorithm

Since we want to estimate model parameters, we switch back the notation of our Markov chain from $X$ to $\theta$. Further, we switch from a discrete to a continuous probability space. Therefore, we replace probability vector $\pi_t$ by density function $p(\theta_t)$ and transition matrix $T$ by transition kernel $K(\theta_{t+1} | \theta_t)$.

\begin{algorithm}
\caption{Metropolis-Hastings algorithm}\label{alg:mh}
\begin{algorithmic}
\State {Initialize $\theta_0$}

        \For{$t \gets 0$ to $T-1$} 
          \State {Draw $u \sim \mathcal{U}_{[0,1]}$}
          \State {Draw candidate $\theta^* \sim q(\theta^*|\theta_{t-1})$}
          \If{$u < \text{min}\{1, \frac{p(\theta^*)q(\theta_t|\theta^*)}{p(\theta_t)q(\theta^*|\theta_t)}\}$} 
              \State $\theta_{t+1} \gets \theta^*$
          \Else
              \State $\theta_{t+1} \gets \theta_t$
\EndIf 
        \EndFor   
\end{algorithmic}
\end{algorithm}

## A short proof

TODO: Use $(X_t)_{t \in \mathbb{N}}$ to denote markov chains (or with $\theta$)

TODO: Read wiki artikles in German about Markov CHains and possibly Mannheim lecture notes.

TODO: CHeck def of limiting distribution and difference to Markov, include definition of limiting distribution e.g. The limiting distribution of a regular Markov chain is a stationary distribution.
If the limiting distribution of a Markov chain is a stationary distribution, then the stationary distribution is unique.

$\text{https://stats.stackexchange.com/questions/48262/what-is-the-difference-between-limiting-and-stationary-distributions}$.

Clearly algo is constructed to obtain limit dist.

To show that the resulting markov chain converges to a unique stationary distribution, we only have to check for irreducibility and aperiodicity and apply the fundamental theorem.

\begin{proof}
First, $\theta_t$ is irreducible because at each step we have a possible probability to reach every value in the range of $\theta$. Second, $\theta_t$ is aperiodic because every value in the range of $\theta$ has a non-zero probability to transist to itself in the next period.
\end{proof}


Show that we get a limit dist, i.e. a unique stationary dist.

\newpage

# References {.unnumbered}

\singlespacing

::: {#refs}
:::


\clearpage

# Statutory Declaration {.unnumbered}

Hiermit versichere ich, dass diese Arbeit von mir persönlich verfasst ist und dass ich keinerlei fremde Hilfe in Anspruch genommen habe.
Ebenso versichere ich, dass diese Arbeit oder Teile daraus weder von mir selbst noch von anderen als Leistungsnachweise andernorts eingereicht wurden.
Wörtliche oder sinngemäße Übernahmen aus anderen Schriften und Veröffentlichungen in gedruckter oder elektronischer Form sind gekennzeichnet.
Sämtliche Sekundärliteratur und sonstige Quellen sind nachgewiesen und in der Bibliographie aufgeführt.
Das Gleiche gilt für graphische Darstellungen und Bilder sowie für alle Internet-Quellen.
Ich bin ferner damit einverstanden, dass meine Arbeit zum Zwecke eines Plagiatsabgleichs in elektronischer Form anonymisiert versendet und gespeichert werden kann.
Mir ist bekannt, dass von der Korrektur der Arbeit abgesehen werden kann, wenn die Erklärung nicht erteilt wird.

```{=tex}
\SignatureAndDate{}
\renewcommand*{\thepage}{ }
```
\noindent I hereby declare that the paper presented is my own work and that I have not called upon the help of a third party.
In addition, I affirm that neither I nor anybody else has submitted this paper or parts of it to obtain credits elsewhere before.
I have clearly marked and acknowledged all quotations or references that have been taken from the works of other.
All secondary literature and other sources are marked and listed in the bibliography.
The same applies to all charts, diagrams and illustrations as well as to all Internet sources.
Moreover, I consent to my paper being electronically stores and sent anonymously in order to be checked for plagiarism.
I am aware that the paper cannot be evaluated and may be graded "failed" ("nicht ausreichend") if the declaration is not made.

\SignatureAndDateEng{}

<!-- Line below depicts the content that should not be counted in the wordcount -->
<!---TC:ignore--->
